apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gbp-ingress
  annotations:
    nginx.ingress.kubernetes.io/websocket-services: "gbp-ws-service"
spec:
  rules:
    - http:
        paths:
          - path: /ws/
            pathType: Prefix
            backend:
              service:
                name: gbp-ws-service
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gbp-fe-service
                port:
                  number: 3000
