apiVersion: apps/v1
kind: Deployment
metadata:
  name: gbp-ws
  labels:
    app: gbp-ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gbp-ws
  template:
    metadata:
      labels:
        app: gbp-ws
    spec:
      containers:
        - name: gbp-ws
          image: frostwyrm9x/gbp_ws:latest
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_ADDR
              valueFrom:
                configMapKeyRef:
                  name: gbp-config
                  key: redis_addr
            - name: REDIS_PWD
              valueFrom:
                configMapKeyRef:
                  name: gbp-config
                  key: redis_pwd
            - name: REDIS_DB
              valueFrom:
                configMapKeyRef:
                  name: gbp-config
                  key: redis_db
---
apiVersion: v1
kind: Service
metadata:
  name: gbp-ws-service
spec:
  type: NodePort
  selector:
    app: gbp-ws
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
